
pretrained_modelpath: "data/deca_model.tar"
dataset:
  training_data: ['me']                     # 使用自定义数据集类型 'me'
  data_root: "/content/ME-DATASET"    # 数据集主目录，必须加引号
  image_size: 224                          # 输入图像尺寸
  K: 1                                     # 每张图像的关键点数量（通常为1）
  isSingle: True                           # 是否为单人图像

model:
  use_tex: True                            # 启用纹理模型
  tex_type: "BFM"                          # 使用 BFM 模板纹理
  extract_tex: True                        # 从图像中提取纹理贴图
  use_detail: False                        # 是否启用 detail 模型（此处关闭）
  use_landmarks: True                      # 启用关键点监督
  use_seg: True                            # 启用 mask 分割监督
  use_pose: False                          # 是否监督姿态（可选）
  uv_size: 256
  n_shape: 100
  n_tex: 50
  n_exp: 50
  n_pose: 6
  n_cam: 3
  n_light: 27
  n_detail: 128
  param_list: ["shape", "tex", "exp", "pose", "cam", "light", "detail"]
  flame_model_path: "data/generic_model.pkl"
  flame_lmk_embedding_path: "data/landmark_embedding.npy"
  tex_path: "data/FLAME_albedo_from_BFM.npz"
  max_z: 0.25
  topology_path: "data/head_template.obj"
  face_eye_mask_path: "data/uv_face_eye_mask.png"
  face_mask_path: "data/uv_face_mask.png"
  fixed_displacement_path: "data/fixed_displacement_256.npy"
  mean_tex_path: "data/mean_texture.jpg"


train:
  batch_size: 1                            # CPU 模式建议使用1
  num_workers: 0                           # CPU-only 环境设为0
  max_epochs: 50                           # 训练轮数
  save_folder: "/content/DECA/OUTPUT3"     # 输出结果保存路径
  log_freq: 10                             # 日志打印频率
  eval_freq: 1                             # 每多少轮进行评估
  save_freq: 5                             # 每多少轮保存模型
  log_dir: 'logs'                          # 默认日志子目录
  vis_dir: "vis_me"
  val_vis_dir: "val_vis_me"

loss:
  landmark_weight: 1.0
  mask_weight: 1.0
  tex_weight: 1.0
  shape_weight: 0.0
  detail_weight: 0.0

device: "cpu"                              # 强制使用 CPU 模式
output_dir: "/content/DECA"                # 用于保存日志、模型等


misc:
  use_vis: True                            # 是否保存可视化结果
  save_images: True                        # 是否保存图像输出
  save_obj: True                           # 是否保存 .obj 文件
  save_mat: True                           # 是否保存 .mat 文件
  save_depth: True                         # 是否保存深度图
  save_kpt: True                           # 是否保存关键点
  rasterizer_type: "pytorch3d"             # 使用 pytorch3d 渲染器（适配 CPU）

# 注册信息（可选）
module_registry:
  name: "P_P_ID_NET"
  version: "v1"
  author: "LEE"
  format: ".wovx"
